# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: docintel.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'docintel.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0e\x64ocintel.proto\x12\x08\x64ocintel\"D\n\rIngestRequest\x12\x10\n\x08\x66ilename\x18\x01 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x02 \x01(\x0c\x12\x10\n\x08\x64oc_type\x18\x03 \x01(\t\"M\n\x0eIngestResponse\x12\x13\n\x0b\x64ocument_id\x18\x01 \x01(\t\x12\x16\n\x0e\x63hunks_created\x18\x02 \x01(\x05\x12\x0e\n\x06status\x18\x03 \x01(\t\"J\n\x0cQueryRequest\x12\x10\n\x08question\x18\x01 \x01(\t\x12\x14\n\x0c\x64ocument_ids\x18\x02 \x03(\t\x12\x12\n\nmax_chunks\x18\x03 \x01(\x05\"T\n\rQueryResponse\x12\r\n\x05token\x18\x01 \x01(\t\x12&\n\x07sources\x18\x02 \x03(\x0b\x32\x15.docintel.SourceChunk\x12\x0c\n\x04\x64one\x18\x03 \x01(\x08\"g\n\x0bSourceChunk\x12\x13\n\x0b\x64ocument_id\x18\x01 \x01(\t\x12\x15\n\rdocument_name\x18\x02 \x01(\t\x12\x12\n\nchunk_text\x18\x03 \x01(\t\x12\x18\n\x10similarity_score\x18\x04 \x01(\x02\"\x1f\n\x0bListRequest\x12\x10\n\x08\x64oc_type\x18\x01 \x01(\t\"9\n\x0c\x44ocumentList\x12)\n\tdocuments\x18\x01 \x03(\x0b\x32\x16.docintel.DocumentMeta\"q\n\x0c\x44ocumentMeta\x12\x13\n\x0b\x64ocument_id\x18\x01 \x01(\t\x12\x10\n\x08\x66ilename\x18\x02 \x01(\t\x12\x10\n\x08\x64oc_type\x18\x03 \x01(\t\x12\x13\n\x0b\x63hunk_count\x18\x04 \x01(\x05\x12\x13\n\x0bingested_at\x18\x05 \x01(\t2\xd7\x01\n\x14\x44ocumentIntelligence\x12\x43\n\x0eIngestDocument\x12\x17.docintel.IngestRequest\x1a\x18.docintel.IngestResponse\x12:\n\x05Query\x12\x16.docintel.QueryRequest\x1a\x17.docintel.QueryResponse0\x01\x12>\n\rListDocuments\x12\x15.docintel.ListRequest\x1a\x16.docintel.DocumentListb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'docintel_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_INGESTREQUEST']._serialized_start=28
  _globals['_INGESTREQUEST']._serialized_end=96
  _globals['_INGESTRESPONSE']._serialized_start=98
  _globals['_INGESTRESPONSE']._serialized_end=175
  _globals['_QUERYREQUEST']._serialized_start=177
  _globals['_QUERYREQUEST']._serialized_end=251
  _globals['_QUERYRESPONSE']._serialized_start=253
  _globals['_QUERYRESPONSE']._serialized_end=337
  _globals['_SOURCECHUNK']._serialized_start=339
  _globals['_SOURCECHUNK']._serialized_end=442
  _globals['_LISTREQUEST']._serialized_start=444
  _globals['_LISTREQUEST']._serialized_end=475
  _globals['_DOCUMENTLIST']._serialized_start=477
  _globals['_DOCUMENTLIST']._serialized_end=534
  _globals['_DOCUMENTMETA']._serialized_start=536
  _globals['_DOCUMENTMETA']._serialized_end=649
  _globals['_DOCUMENTINTELLIGENCE']._serialized_start=652
  _globals['_DOCUMENTINTELLIGENCE']._serialized_end=867
# @@protoc_insertion_point(module_scope)
