# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import docintel_pb2 as docintel__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in docintel_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class DocumentIntelligenceStub(object):
    """this is like your Express router. It defines three endpoints (called RPCs instead of routes).
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.IngestDocument = channel.unary_unary(
                '/docintel.DocumentIntelligence/IngestDocument',
                request_serializer=docintel__pb2.IngestRequest.SerializeToString,
                response_deserializer=docintel__pb2.IngestResponse.FromString,
                _registered_method=True)
        self.Query = channel.unary_stream(
                '/docintel.DocumentIntelligence/Query',
                request_serializer=docintel__pb2.QueryRequest.SerializeToString,
                response_deserializer=docintel__pb2.QueryResponse.FromString,
                _registered_method=True)
        self.ListDocuments = channel.unary_unary(
                '/docintel.DocumentIntelligence/ListDocuments',
                request_serializer=docintel__pb2.ListRequest.SerializeToString,
                response_deserializer=docintel__pb2.DocumentList.FromString,
                _registered_method=True)


class DocumentIntelligenceServicer(object):
    """this is like your Express router. It defines three endpoints (called RPCs instead of routes).
    """

    def IngestDocument(self, request, context):
        """Ingest a document: chunk it, embed it, store it
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Query(self, request, context):
        """Query across ingested documents with RAG
        stream means instead of returning one response, the server sends multiple QueryResponse messages back over time.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListDocuments(self, request, context):
        """List ingested documents
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DocumentIntelligenceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'IngestDocument': grpc.unary_unary_rpc_method_handler(
                    servicer.IngestDocument,
                    request_deserializer=docintel__pb2.IngestRequest.FromString,
                    response_serializer=docintel__pb2.IngestResponse.SerializeToString,
            ),
            'Query': grpc.unary_stream_rpc_method_handler(
                    servicer.Query,
                    request_deserializer=docintel__pb2.QueryRequest.FromString,
                    response_serializer=docintel__pb2.QueryResponse.SerializeToString,
            ),
            'ListDocuments': grpc.unary_unary_rpc_method_handler(
                    servicer.ListDocuments,
                    request_deserializer=docintel__pb2.ListRequest.FromString,
                    response_serializer=docintel__pb2.DocumentList.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'docintel.DocumentIntelligence', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('docintel.DocumentIntelligence', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class DocumentIntelligence(object):
    """this is like your Express router. It defines three endpoints (called RPCs instead of routes).
    """

    @staticmethod
    def IngestDocument(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/docintel.DocumentIntelligence/IngestDocument',
            docintel__pb2.IngestRequest.SerializeToString,
            docintel__pb2.IngestResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Query(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/docintel.DocumentIntelligence/Query',
            docintel__pb2.QueryRequest.SerializeToString,
            docintel__pb2.QueryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListDocuments(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/docintel.DocumentIntelligence/ListDocuments',
            docintel__pb2.ListRequest.SerializeToString,
            docintel__pb2.DocumentList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
